apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "my-gateway" }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: gateway
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.port | default 80 }}
    targetPort: 8080
    protocol: TCP
    name: http
  - port: {{ .Values.service.managementPort | default 8090 }}
    targetPort: 8090
    protocol: TCP
    name: management
  selector:
    app: gateway
---
{{- if .Values.service.type | default "ClusterIP" | eq "LoadBalancer" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "my-gateway" }}-lb
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: gateway
    service-type: loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: gateway
{{- end }}
