apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service-account
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-ingress-reader
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-ingress-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-ingress-reader
subjects:
- kind: ServiceAccount
  name: gateway-service-account
  namespace: {{ .Values.namespace | default "default" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-config-reader
  namespace: {{ .Values.namespace | default "default" }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-config-reader-binding
  namespace: {{ .Values.namespace | default "default" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-config-reader
subjects:
- kind: ServiceAccount
  name: gateway-service-account
  namespace: {{ .Values.namespace | default "default" }}
