apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: {{ .Values.namespace | default "default" }}
data:
  application.yml: |
    management:
      endpoint:
        health:
          show-details: when_authorized
        gateway:
          enabled: true
      endpoints:
        web:
          exposure:
            include: "*"
      server:
        port: 8090
      metrics:
        export:
          wavefront:
            enabled: false

    spring:
      cloud:
        loadbalancer:
          cache:
            ttl: 5S
        gateway:
          filter:
            token-relay:
              enabled: false
          actuator:
            verbose:
              enabled: false
          kubernetes:
            ingress:
              enabled: {{ .Values.ingress.enabled | default true }}
              namespace: {{ .Values.namespace | default "default" }}
              refresh-interval: {{ .Values.ingress.refreshInterval | default 30 }}
              cache-enabled: {{ .Values.ingress.cacheEnabled | default true }}
              cache-expiration: {{ .Values.ingress.cacheExpiration | default 300 }}
              tls-enabled: {{ .Values.ingress.tls.enabled | default true }}
              default-service-port: {{ .Values.service.port | default 80 }}
              path-rewrite-enabled: {{ .Values.ingress.pathRewrite.enabled | default true }}
              path-rewrite-pattern: "{{ .Values.ingress.pathRewrite.pattern | default "/(.*)" }}"
              path-rewrite-replacement: "{{ .Values.ingress.pathRewrite.replacement | default "/$1" }}"
      session:
        timeout: 30m
      kubernetes:
        discovery:
          enabled: true
        config:
          enabled: true
    sso:
      roles-attribute-name: roles

    logging:
      level:
        ti.gateway.kubernetes.ingress: {{ .Values.logging.level.ingress | default "INFO" }}
        org.springframework.cloud.gateway: {{ .Values.logging.level.gateway | default "INFO" }}
        io.kubernetes.client: {{ .Values.logging.level.kubernetes | default "WARN" }}
