{
 "title": "Spring Cloud Gateway for Kubernetes",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gatewayName",
    "label": "Gateway Name",
    "query": {
     "query": "label_values(spring_cloud_gateway_routes_count, gateway_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(spring_cloud_gateway_routes_count, kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Routes count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_cloud_gateway_routes_count{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Response Success Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (spring_cloud_gateway_requests_seconds_count{outcome=~\"SUCCESSFUL|REDIRECTION\",gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"}) / sum (spring_cloud_gateway_requests_seconds_count{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"})  * 100"
    }
   ]
  },
  {
   "title": "Response Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (spring_cloud_gateway_requests_seconds_count{outcome!~\"SUCCESSFUL|REDIRECTION\",gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"}) / sum (spring_cloud_gateway_requests_seconds_count{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"})  * 100"
    }
   ]
  },
  {
   "title": "Rate Limited Requests Rate",
   "type": "stat",
   "description": "Rate of requests that were rate limited",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (spring_cloud_gateway_requests_seconds_count{status=\"TOO_MANY_REQUESTS\", gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"}) / sum (spring_cloud_gateway_requests_seconds_count{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Average Response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_sum{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"}) / sum(spring_cloud_gateway_requests_seconds_count{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"}) "
    }
   ]
  },
  {
   "title": "Average Response time",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "sum by (httpMethod, path) (spring_cloud_gateway_requests_seconds_sum{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"}) /  sum by (httpMethod, path)(spring_cloud_gateway_requests_seconds_count{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Max Response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(spring_cloud_gateway_requests_seconds_sum{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Max Response time",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "max by (httpMethod,path) (spring_cloud_gateway_requests_seconds_sum{gateway_name=~\"$gatewayName\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total API usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count) ",
     "legendFormat": "Request count"
    }
   ]
  },
  {
   "title": "Total API usage by path",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count) by (path, httpMethod)",
     "legendFormat": "{{httpMethod}} {{path}}"
    }
   ]
  },
  {
   "title": "Total API usage by path",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count) by (path, httpMethod)",
     "legendFormat": "{{httpMethod}} {{path}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome!~\"SUCCESSFUL|REDIRECTION\"})",
     "legendFormat": "Error count"
    }
   ]
  },
  {
   "title": "Errors by path",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome!~\"SUCCESSFUL|REDIRECTION\"}) by (path, httpMethod)",
     "legendFormat": "{{httpMethod}} {{path}}"
    }
   ]
  },
  {
   "title": "Errors by path",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome!~\"SUCCESSFUL|REDIRECTION\"}) by (path, httpMethod)",
     "legendFormat": "{{httpMethod}} {{path}}"
    }
   ]
  },
  {
   "title": "Successful authentications by path",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome=~\"SUCCESSFUL|REDIRECTION\", hasAuthenticationFilter=\"true\"}) by (path, httpMethod) "
    }
   ]
  },
  {
   "title": "Forbidden Error Rate by path",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{status=\"FORBIDDEN\"}) by (path, httpMethod) / sum(spring_cloud_gateway_requests_seconds_count) by (path, httpMethod) * 100"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{status=\"FORBIDDEN\"}) by (path, httpMethod) "
    }
   ]
  },
  {
   "title": "Unsuccessful authentications by path",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{status=\"UNAUTHORIZED\"}) by (path, httpMethod) / sum(spring_cloud_gateway_requests_seconds_count) by (path, httpMethod) * 100"
    },
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{status=\"UNAUTHORIZED\"}) by (path, httpMethod) "
    }
   ]
  }
 ]
}