apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tigatewaymappings.tigateway.cn
spec:
  group: tigateway.cn
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gatewayRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                routeConfigRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                # TiGateway specific mapping properties
                ingressRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  description: Reference to a Kubernetes Ingress resource
                priority:
                  type: integer
                  default: 0
                  description: Priority for route ordering (higher values have higher priority)
                enabled:
                  type: boolean
                  default: true
                  description: Whether this mapping is enabled

  scope: Namespaced
  names:
    plural: tigatewaymappings
    singular: tigatewaymapping
    kind: TiGatewayMapping
    shortNames:
      - tgm
      - tgms
