apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tigatewayrouteconfigs.tigateway.cn
spec:
  group: tigateway.cn
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                service:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                    port:
                      type: integer
                    predicates:
                      type: array
                      items:
                        type: string
                    filters:
                      type: array
                      items:
                        type: string
                    ssoEnabled:
                      type: boolean
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                        description: An optional title, intended to apply to all operations in this path.
                      description:
                        type: string
                        description: An optional description, intended to apply to all operations in this path.
                      uri:
                        type: string
                      predicates:
                        type: array
                        items:
                          type: string
                      filters:
                        type: array
                        items:
                          type: string
                      order:
                        type: integer
                      ssoEnabled:
                        type: boolean
                      tokenRelay:
                        type: boolean
                        default: false
                      tags:
                        type: array
                        items:
                          type: string
                      model:
                        type: object
                        properties:
                          requestBody:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            description: The request body as specified by https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#requestBodyObject
                          responses:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            description: The responses of an operation as specified by https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#responsesObject
                      # TiGateway specific route properties
                      ingressSource:
                        type: string
                        description: Source of the route (e.g., 'kubernetes-ingress', 'manual')
                      host:
                        type: string
                        description: Host header for the route
                      pathType:
                        type: string
                        enum: ["Prefix", "Exact", "ImplementationSpecific"]
                        default: "Prefix"
                        description: Path matching type
                      tlsEnabled:
                        type: boolean
                        default: false
                        description: Whether TLS is enabled for this route
                basicAuth:
                  type: object
                  properties:
                    secret:
                      type: string
                      description: The secret name containing basic auth credentials. It should contain a username and password keys.
                openapi:
                  type: object
                  properties:
                    components:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      description: Holds a set of reusable objects for different aspects of the OAS, as defined by https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#componentsObject
                # TiGateway specific configuration
                ingress:
                  type: object
                  properties:
                    autoDiscovery:
                      type: boolean
                      default: true
                      description: Automatically discover routes from Kubernetes Ingress resources
                    namespace:
                      type: string
                      default: "default"
                      description: Namespace to watch for Ingress resources
                    labelSelector:
                      type: string
                      description: Label selector to filter Ingress resources
                    annotationSelector:
                      type: string
                      description: Annotation selector to filter Ingress resources
                    refreshInterval:
                      type: integer
                      default: 30
                      description: Interval in seconds to refresh Ingress routes
                    cacheEnabled:
                      type: boolean
                      default: true
                      description: Enable caching for Ingress resources
                    cacheExpiration:
                      type: integer
                      default: 300
                      description: Cache expiration in seconds for Ingress resources
                    ingressClass:
                      type: string
                      default: "tigateway"
                      description: IngressClass name to filter Ingress resources
                    ingressClassSelector:
                      type: string
                      description: IngressClass selector to filter Ingress resources
          anyOf:
            - properties:
                spec:
                  required: ["service"]
            - properties:
                spec:
                  properties:
                    routes:
                      items:
                        required: ["uri"]

  scope: Namespaced
  names:
    plural: tigatewayrouteconfigs
    singular: tigatewayrouteconfig
    kind: TiGatewayRouteConfig
    shortNames:
      - tgrc
      - tgrcs
