# TiGateway ConfigMap Storage Configuration
spring:
  cloud:
    gateway:
      # 启用ConfigMap存储
      storage:
        configmap:
          enabled: true
          name: tigateway-app-config
          namespace: default
          app-info-key-prefix: "app."
          server-info-key-prefix: "server."
          auto-refresh: true
          refresh-interval: 30
          cache-enabled: true
          cache-expiration: 300
          create-default-config: true
          default-app:
            app-key: default-app
            app-secret: default-secret
            name: Default Application
            desc: Default application for TiGateway
            type: 1
            status: 1
            default-servers:
              - user-service
              - order-service
              - payment-service
      
      # 应用配置
      app:
        skip: false
        app-id: X-GW-APPID
        timestamp: X-GW-Timestamp
        sign: X-GW-SIGN
        duration-mt: 300000
      
      # 服务配置
      server:
        skip: false
      
      # 缓存配置
      cache:
        should-use-read-only-server-cache: true
        server-cache-auto-expiration-in-seconds: 180
        initial-capacity-of-server-cache: 100
        server-cache-update-interval-ms: 30000
        skip: false

# 日志配置
logging:
  level:
    ti.gateway.base.storage.configmap: DEBUG
    io.kubernetes.client: INFO
