apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: springcloudgateways.tanzu.vmware.com
spec:
  group: tanzu.vmware.com
  scope: Namespaced
  preserveUnknownFields: false
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.count
          statusReplicasPath: .status.replicas
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                count:
                  type: integer
                  exclusiveMinimum: false
                java-opts:
                  type: string
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                sso:
                  type: object
                  properties:
                    secret:
                      type: string
                    roles-attribute-name:
                      type: string
                    inactive-session-expiration-in-minutes:
                      type: integer
                      description: Time to life of inactive sessions, 0 means infinite (in minutes).
                api:
                  type: object
                  properties:
                    groupId:
                      type: string
                      pattern: '^[a-z0-9]+(-[a-z0-9]+)*$'
                    title:
                      type: string
                    description:
                      type: string
                    documentation:
                      type: string
                      description: The URL of an external resource for extended documentation. Value MUST be in the format of a URL.
                    version:
                      type: string
                      default: unspecified
                    serverUrl:
                      type: string
                      description: Publicly accessible user-facing URL of this Gateway instance.
                    cors:
                      type: object
                      properties:
                        maxAge:
                          type: integer
                          description: Configure how long, in seconds, the response from a pre-flight request can be cached by clients.
                        allowCredentials:
                          type: boolean
                          description: Whether user credentials are supported.
                        allowedOrigins:
                          type: array
                          items:
                            type: string
                          description: >
                            Set the origins to allow, e.g. "https://domain1.com".
                            The special value "*" allows all domains.
                        allowedMethods:
                          type: array
                          items:
                            type: string
                          description: >
                            Set the HTTP methods to allow, e.g. "GET", "POST", "PUT", etc.
                            The special value "*" allows all methods.
                            If not set, only "GET" and "HEAD" are allowed.
                        allowedHeaders:
                          type: array
                          items:
                            type: string
                          description: >
                            Set the list of headers that a pre-flight request can list as allowed for use during an actual request.
                            The special value "*" allows actual requests to send any header.
                            A header name is not required to be listed if it is one of: Cache-Control, Content-Language, Expires, Last-Modified, or Pragma.
                        exposedHeaders:
                          type: array
                          items:
                            type: string
                          description: >
                            Set the list of response headers other than simple headers (i.e. Cache-Control, Content-Language, Content-Type, Expires, Last-Modified, or Pragma) that an actual response might have and can be exposed.
                            Note that "*" is not a valid exposed header value
                        allowedOriginPatterns:
                          type: array
                          items:
                            type: string
                          description: >
                            Alternative to allowedOrigins that supports more flexible origins patterns with "*" anywhere in the host name in addition to port lists.
                            In contrast to allowedOrigins which only supports "*" and cannot be used with allowCredentials, when an allowedOriginPattern is matched, the Access-Control-Allow-Origin response header is set to the matched origin and not to "*" nor to the pattern.
                            Therefore allowedOriginPatterns can be used in combination with allowCredentials set to true.
                        perRoute:
                          type: object
                          description: >
                            A map of URL Patterns to Spring Framework CorsConfiguration. See https://cloud.spring.io/spring-cloud-gateway/reference/html/#cors-configuration for an example.
                          additionalProperties:
                            type: object
                            properties:
                              maxAge:
                                type: integer
                                description: Configure how long, in seconds, the response from a pre-flight request can be cached by clients.
                              allowCredentials:
                                type: boolean
                                description: Whether user credentials are supported.
                              allowedOrigins:
                                type: array
                                items:
                                  type: string
                                description: >
                                  Set the origins to allow, e.g. "https://domain1.com".
                                  The special value "*" allows all domains.
                              allowedMethods:
                                type: array
                                items:
                                  type: string
                                description: >
                                  Set the HTTP methods to allow, e.g. "GET", "POST", "PUT", etc.
                                  The special value "*" allows all methods.
                                  If not set, only "GET" and "HEAD" are allowed.
                              allowedHeaders:
                                type: array
                                items:
                                  type: string
                                description: >
                                  Set the list of headers that a pre-flight request can list as allowed for use during an actual request.
                                  The special value "*" allows actual requests to send any header.
                                  A header name is not required to be listed if it is one of: Cache-Control, Content-Language, Expires, Last-Modified, or Pragma.
                              exposedHeaders:
                                type: array
                                items:
                                  type: string
                                description: >
                                  Set the list of response headers other than simple headers (i.e. Cache-Control, Content-Language, Content-Type, Expires, Last-Modified, or Pragma) that an actual response might have and can be exposed.
                                  Note that "*" is not a valid exposed header value
                              allowedOriginPatterns:
                                type: array
                                items:
                                  type: string
                                description: >
                                  Alternative to allowedOrigins that supports more flexible origins patterns with "*" anywhere in the host name in addition to port lists.
                                  In contrast to allowedOrigins which only supports "*" and cannot be used with allowCredentials, when an allowedOriginPattern is matched, the Access-Control-Allow-Origin response header is set to the matched origin and not to "*" nor to the pattern.
                                  Therefore allowedOriginPatterns can be used in combination with allowCredentials set to true.
                extensions:
                  type: object
                  properties:
                    custom:
                      type: array
                      items:
                        type: string
                      description: >
                        Array of custom extensions to load (name must match the ConfigMap or PersistentVolumeClaim name)
                    secretsProviders:
                      type: array
                      items:
                        type: object
                        properties:
                          vault:
                            type: object
                            properties:
                              path:
                                type: string
                                description: Vault secrets' path (e.g. 'my-secrets/context').
                              roleName:
                                type: string
                                description: Vault rolename with access to the secrets according to the Vault policies.
                              authPath:
                                type: string
                                description: Authentication path for the Kubernetes auth method.
                            description: >
                              Vault integration configuration parameters
                          name:
                            type: string
                      description: >
                        Array of secret providers. These are identified by a name and follow conventions similar to `volumes`. Currently supported Vault.
                    filters:
                      type: object
                      properties:
                        apiKey:
                          type: object
                          description: >
                            API Key specific configurations
                          properties:
                            enabled:
                              type: boolean
                            secretsProviderName:
                              type: string
                        jwtKey:
                          type: object
                          description: >
                            JWT Key specific configurations
                          properties:
                            enabled:
                              type: boolean
                            secretsProviderName:
                              type: string
                observability:
                  type: object
                  properties:
                    metrics:
                      type: object
                      properties:
                        wavefront:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: >
                                If wavefront metrics should be pushed
                        prometheus:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: >
                                If a prometheus endpoint should be exposed
                            annotations:
                              type: object
                              properties:
                                enabled:
                                  type: boolean
                                  description: >
                                    If scrapping annotations should be included in the Pod
                            serviceMonitor:
                              type: object
                              properties:
                                enabled:
                                  type: boolean
                                  description: >
                                    If a Prometheus ServiceMonitor should be added
                                labels:
                                  additionalProperties:
                                    type: string
                                  description: >
                                    Labels to add to the service monitor, e.g. to be picked up by the Prometheus serviceMonitorSelector
                                  type: object
                    tracing:
                      type: object
                      properties:
                        wavefront:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: >
                                If wavefront traces should be pushed
                    wavefront:
                      type: object
                      properties:
                        secret:
                          type: string
                        source:
                          type: string
                          description: >
                            The wavefront source.
                        application:
                          type: string
                          description: >
                            The wavefront application name.
                        service:
                          type: string
                          description: >
                            The wavefront service name.
                serviceAccount:
                  type: object
                  properties:
                    name:
                      type: string
                  description: >
                    ServiceAccount associated to the Gateway instance
                securityContext:
                  type: object
                  properties:
                    runAsUser:
                      type: integer
                    runAsGroup:
                      type: integer
                    fsGroup:
                      type: integer
                      default: 1000
                  description: >
                    SecurityContext applied to the Gateway pod(s).
                tls:
                  type: array
                  items:
                    type: object
                    properties:
                      hosts:
                        type: array
                        items:
                          type: string
                      secretName:
                        type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      status:
                        type: string
                        description: The status of the condition, either True, False or Unknown.
                      lastTransitionTime:
                        type: string
                        description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      reason:
                        type: string
                        description: The reason for the condition's last transition (a single word in CamelCase).
                  description: List of status conditions.
  names:
    plural: springcloudgateways
    singular: springcloudgateway
    kind: SpringCloudGateway
    shortNames:
      - scg
      - scgs
