# TiGateway 文档站点配置
# GitHub Pages Jekyll 配置

# 站点基本信息
title: TiGateway 文档
description: TiGateway - 基于 Spring Cloud Gateway 的 Kubernetes 原生 API 网关
author: TiGateway Team
email: support@tigateway.cn
url: https://tigateway.github.io
baseurl: /tigateway

# 构建配置
markdown: kramdown
highlighter: rouge
theme: minima

# 插件配置
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore
  - .gitattributes
  - GITHUB_PAGES_SETUP.md

# 自定义变量
tigateway:
  version: "1.0.0"
  latest_version: "1.0.0"
  repository: "https://github.com/tigateway/tigateway"
  issues: "https://github.com/tigateway/tigateway/issues"
  discussions: "https://github.com/tigateway/tigateway/discussions"