# TiGateway 文档站点 Gemfile

source "https://rubygems.org"

# Jekyll 版本
gem "jekyll", "~> 4.3.0"

# 主题
gem "minima", "~> 2.5"

# 插件
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-optional-front-matter", "~> 0.3"

# 开发依赖
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-redirect-from", "~> 0.16"
  gem "jekyll-optional-front-matter", "~> 0.3"
end

# Windows 不支持
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# 性能优化
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# 代码高亮
gem "rouge", "~> 4.0"

# 分页
gem "kramdown-parser-gfm", "~> 1.1"

# 本地开发
gem "webrick", "~> 1.7"
